[colors]
ansi = [
    '#e0e0e0',
    '#972500',
    '#315b00',
    '#70480f',
    '#2544bb',
    '#8f0075',
    '#30517f',
    '#000000',
]
brights = [
    '#d7d7d7',
    '#a60000',
    '#005e00',
    '#813e00',
    '#0031a9',
    '#721045',
    '#00538b',
    '#000000',
]
cursor_bg = '#000000'
cursor_border = '#000000'
cursor_fg = '#ffffff'
foreground = '#000000'
background = '#ffffff'
selection_bg = '#e8dfd1'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Modus-Operandi'
