[colors]
ansi = [
    '#191a1b',
    '#ff8059',
    '#44bc44',
    '#d0bc00',
    '#2fafff',
    '#feacd0',
    '#00d3d0',
    '#ffffff',
]
brights = [
    '#1e1e1e',
    '#ef8b50',
    '#70b900',
    '#c0c530',
    '#79a8ff',
    '#f78fe7',
    '#4ae2f0',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#000000'
foreground = '#ffffff'
background = '#000000'
selection_bg = '#282e46'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Modus-Vivendi'
